/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadEuroChem;

import java.util.List;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import cadEuroChem.MultiPainel;
/**
 *
 * @author phsto
 */
public class LoginJFrame extends javax.swing.JFrame {
    private final List<Usuario> usuariosAutorizados;
    private Usuario usuarioCadastrado;
    
    public void setUsuarioCadastrado(Usuario usuario){
        this.usuarioCadastrado = usuario;
    }
    
    /**
     * Creates new form Cadastro
     */
    public LoginJFrame() {
        initComponents();
        //COLOCAR ICONE DO PROGRAMA NA PÁGINA
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/cadEuroChem/img/logoIcon.png")));
        
        usuariosAutorizados = new ArrayList<>();
        usuariosAutorizados.add(new Usuario("admin", "admin"));
        usuariosAutorizados.add(new Usuario("phillipe", "phillipe"));
    }
    private boolean verificarCredenciais(String nome, String senha) {
        // Verifique se existe um usuário com as credenciais fornecidas na lista de usuários autorizados
        for (Usuario usuario : usuariosAutorizados) {
            if (usuario.getName().equals(nome) && usuario.getPassword().equals(senha)) {
                return true; // Credenciais corretas
            }
        }
        return false; // Credenciais incorretas
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotoesEstoque = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        buttonSave = new javax.swing.JButton();
        buttonClose = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PMSYS v0.1");
        setSize(new java.awt.Dimension(1238, 720));

        jPanel1.setBackground(new java.awt.Color(51, 100, 225));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 237, 237)));
        jPanel1.setPreferredSize(new java.awt.Dimension(556, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Aveline", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(222, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadEuroChem/img/logoIcon.png"))); // NOI18N
        jLabel1.setText("EUROCHEM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 24, -1, -1));

        labelNome.setFont(new java.awt.Font("Aveline", 0, 18)); // NOI18N
        labelNome.setForeground(new java.awt.Color(222, 255, 255));
        labelNome.setText("NOME:");
        jPanel1.add(labelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 185, -1, -1));

        Name.setBackground(new java.awt.Color(255, 255, 255));
        Name.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 175, 262, 35));

        labelSenha.setFont(new java.awt.Font("Aveline", 0, 18)); // NOI18N
        labelSenha.setForeground(new java.awt.Color(222, 255, 255));
        labelSenha.setText("SENHA:");
        jPanel1.add(labelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 218, 67, 37));

        buttonSave.setBackground(new java.awt.Color(0, 255, 0));
        buttonSave.setFont(new java.awt.Font("Aveline", 0, 11)); // NOI18N
        buttonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadEuroChem/img/inco1.png"))); // NOI18N
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 312, 94, 56));

        buttonClose.setBackground(new java.awt.Color(255, 51, 51));
        buttonClose.setFont(new java.awt.Font("Aveline", 0, 11)); // NOI18N
        buttonClose.setForeground(new java.awt.Color(222, 255, 255));
        buttonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadEuroChem/img/return.png"))); // NOI18N
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });
        jPanel1.add(buttonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 312, 94, 56));

        Password.setBackground(new java.awt.Color(255, 255, 255));
        Password.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 216, 262, 37));

        jLabel4.setFont(new java.awt.Font("Aveline", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LOGIN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void limparTexto(){
        Name.setText("");
        Password.setText("");
    }
    
    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        String nomeAux = Name.getText();
        String senhaAux = Password.getText(); // Use getPassword() para obter a senha como uma matriz de caracteres

        if (verificarCredenciais(nomeAux, senhaAux)) {
            // Credenciais corretas, abra o MultiPainel
            this.setVisible(false);
            MultiPainel multiPainel = new MultiPainel(this); // Passe uma referência para esta instância de LoginJFrame
            multiPainel.setVisible(true);
        } else {
            // Credenciais incorretas
            System.out.println("Acesso negado"); // Apenas para depuração
            JOptionPane.showMessageDialog(null, "Acesso negado");
        }
        if (verificarCredenciais(nomeAux, senhaAux) || (usuarioCadastrado != null &&
            usuarioCadastrado.getName().equals(nomeAux) && usuarioCadastrado.getPassword().equals(senhaAux))) {
            // Credenciais corretas, abra o MultiPainel
            this.setVisible(false);
            MultiPainel multiPainel = new MultiPainel(this);
            multiPainel.setVisible(true);
        } else {
            // Credenciais incorretas
            System.out.println("Acesso negado"); // Apenas para depuração
            JOptionPane.showMessageDialog(null, "Acesso negado");
        }
        
        /*this.setVisible(false);
        System.out.println("NOME: " + nomeAux + "\nSenha: " + senhaAux);
        JOptionPane.showMessageDialog(null, "ACESSO PERMITIDO");
        MultiPainel multiPainel = new MultiPainel(this);
        multiPainel.setVisible(true);
        */     
        limparTexto();
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonCloseActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(SingupJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    
    //MultiPainel multiPainel = new MultiPainel(lo); // Crie uma instância de MultiPainel
    
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
        new LoginJFrame().setVisible(true);
    });
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonSave;
    private javax.swing.ButtonGroup grupoBotoesEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    // End of variables declaration//GEN-END:variables
}
