/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadEuroChem;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import cadEuroChem.MultiPainel;
/**
 *
 * @author phsto
 */
public class MultiPainel extends javax.swing.JFrame {
    private ArrayList<Fornecedor> fornecedor = new ArrayList<>();
    private LoginJFrame loginJFrame;

    public MultiPainel(LoginJFrame loginFrame) {
        initComponents();
        // COLOCAR O ÍCONE DO PROGRAMA NO CANTO DA PÁGINA
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/cadEuroChem/img/logoIcon.png")));
        this.loginJFrame = loginFrame; // Armazene a referência para uso posterior
        buttonCadastrar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Código para abrir a janela de cadastro (SingupJFrame)
                SingupJFrame singupFrame = new SingupJFrame();
                singupFrame.setVisible(true);
            }
        });
    }
    public Fornecedor getCadastroFornecedor(){
        String auxNameFornecedor = campoNameFornecedor.getText(); // Obtém o valor do campo de nome
        String auxNumFornecedor = campoNumeroFornecedor.getText(); // Obtém o valor do campo de número
        return new Fornecedor(auxNameFornecedor, auxNumFornecedor);
    }
    
    private void limparTexto(){
        campoNameFornecedor.setText("");
        campoNumeroFornecedor.setText("");
    }
    private MultiPainel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttonSaveFornecedor = new javax.swing.JButton();
        buttonClearFornecedor = new javax.swing.JButton();
        buttonCloseFornecedor = new javax.swing.JButton();
        campoNumeroFornecedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoNameFornecedor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        buttonCadastrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        buttonCloseClose = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PMSYS v0.1");
        setPreferredSize(new java.awt.Dimension(554, 410));
        setSize(new java.awt.Dimension(1238, 720));

        jTabbedPane1.setBackground(new java.awt.Color(51, 100, 225));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(606, 383));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(606, 383));
        jTabbedPane1.setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(51, 100, 225));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(556, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Aveline", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PMSYS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 48, 180, 48));

        jLabel2.setFont(new java.awt.Font("Aveline", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("V0.1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 48, -1, 12));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadEuroChem/img/logoIcon.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 24, -1, -1));

        jTabbedPane1.addTab("HOME", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 100, 225));
        jPanel2.setMinimumSize(new java.awt.Dimension(606, 383));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonSaveFornecedor.setBackground(new java.awt.Color(0, 255, 0));
        buttonSaveFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadEuroChem/img/inco1.png"))); // NOI18N
        buttonSaveFornecedor.setMaximumSize(new java.awt.Dimension(98, 74));
        buttonSaveFornecedor.setMinimumSize(new java.awt.Dimension(98, 74));
        buttonSaveFornecedor.setPreferredSize(new java.awt.Dimension(98, 74));
        jPanel2.add(buttonSaveFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 252, 86, 61));

        buttonClearFornecedor.setBackground(new java.awt.Color(255, 255, 51));
        buttonClearFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadEuroChem/img/imgClear.png"))); // NOI18N
        buttonClearFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearFornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(buttonClearFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 252, 86, 61));

        buttonCloseFornecedor.setBackground(new java.awt.Color(255, 51, 51));
        buttonCloseFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadEuroChem/img/return.png"))); // NOI18N
        jPanel2.add(buttonCloseFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 252, 86, 61));

        campoNumeroFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        campoNumeroFornecedor.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jPanel2.add(campoNumeroFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 144, 276, 24));

        jLabel6.setFont(new java.awt.Font("Aveline", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NOME:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 96, -1, -1));

        jLabel7.setFont(new java.awt.Font("Aveline", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DADOS DO FORNECEDOR");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 12, -1, -1));

        jLabel8.setFont(new java.awt.Font("Aveline", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NÚMERO:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 144, -1, -1));

        campoNameFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        campoNameFornecedor.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jPanel2.add(campoNameFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 96, 276, 24));

        jTabbedPane1.addTab("FORNECEDOR", jPanel2);

        jPanel3.setBackground(new java.awt.Color(51, 100, 225));

        jLabel4.setFont(new java.awt.Font("Aveline", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TIME:");

        jLabel5.setFont(new java.awt.Font("Aveline", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATE:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TENPO", jPanel3);

        jPanel5.setBackground(new java.awt.Color(51, 100, 225));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("USUÁRIO", jPanel5);

        jPanel6.setBackground(new java.awt.Color(51, 100, 225));

        buttonCadastrar.setBackground(new java.awt.Color(0, 255, 0));
        buttonCadastrar.setFont(new java.awt.Font("Aveline", 1, 24)); // NOI18N
        buttonCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        buttonCadastrar.setText("CADASTRAR");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CADASTRO", jPanel6);

        jPanel4.setBackground(new java.awt.Color(51, 100, 225));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonCloseClose.setBackground(new java.awt.Color(255, 51, 51));
        buttonCloseClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadEuroChem/img/return.png"))); // NOI18N
        buttonCloseClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseCloseActionPerformed(evt);
            }
        });
        jPanel4.add(buttonCloseClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 168, 330, 74));

        jLabel9.setFont(new java.awt.Font("Aveline", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ATÉ LOGO!");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 48, 324, 72));

        jTabbedPane1.addTab("SAIR", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCloseCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonCloseCloseActionPerformed

    private void buttonClearFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearFornecedorActionPerformed
        // TODO add your handling code here:
        limparTexto();
    }//GEN-LAST:event_buttonClearFornecedorActionPerformed

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MultiPainel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonClearFornecedor;
    private javax.swing.JButton buttonCloseClose;
    private javax.swing.JButton buttonCloseFornecedor;
    private javax.swing.JButton buttonSaveFornecedor;
    private javax.swing.JTextField campoNameFornecedor;
    private javax.swing.JTextField campoNumeroFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
